package WebSocket;

public enum ChatMessageVOTypes {
    createThread(1),
    message(2) ,
    sent (3),
    delivery(4),
    seen(5),
    ping(6),
    block(7),
    unblock(8),
    leaveThread(9),
    rename(10), // not implemented yet!
    addParticipant(11),
    getStatus(12), // not implemented yet!
    getContacts(13),
    getThreads(14),
    getHistory(15),
    changeType(16), // not implemented yet!
    removedFromThread(17),
    removeParticipant(18),
    muteThread(19),
    unmuteThread(20),
    updateThreadInfo(21),
    forwardMessage(22),
    userInfo(23),
    userStatus(24),// not implemented yet!
    getBlocked(25),
    relationInfo(26), // not implemented yet!
    threadParticipants(27),
    editMessage(28),
    deleteMessage(29),
    lastMessageSeenUpdated(31),
    messageDeliveredToParticipants(32),
    getMessageSeenParticipants(33),
    isNameAvailable(34),
    joinThread(39),
    botMessage(40),
    spamPvThread(41),
    setRuleToUser(42),
    removeRoleFromUser(43),
    clearHistory(44),
    systemMessage(46),
    getNotSeenDuration(47),
    pinThread(48),
    unpinThread(49),
    pinMessage(50),
    unpinMessage(51),
    setProfile(52),
    changeThreadType(53),
    getCurrentUserRoles(54),
    getReportReasons(56), // not implemented yet!,
    reportThread(57),
    reportUser(58),
    reportMessage(59),
    contactsLastSeen(60),
    allUnreadMessageCount(61),
    createBot(62),
    defineBotCommand(63),
    startBot(64),
    stopBot(65),
    lastMessageDeleted(66),
    lastMessageEdited(67),
    contactSynced(90),
    logout(100),
    statusPing(101),
    closeThread(102),
    removeBotCommands(104),
    registerAssistant(107),
    deacticveAssistant(108),
    getAssistants(109),
    getAssistantHistory(115),
    blockAssistant(116),
    unblockAssistant(117),
    blockedAssistnts(118),
    getUserBots(120),
    mutualGroups(130),
    deleteThread(151),
    createTag(140),
    editTag(141),
    deleteTag(142),
    addTagParticipants(143),
    removeTagParticipants(144),
    tagList(145),
    getTagParticipants(-4),
    exportChats(152),
    threadContactNameUpdated(220),
    archiveThread(223),
    unarchiveThread(224),
    threadsUnreadCount(233),

            // CALL
    startCallRequest(70),
    acceptCall(71) ,// never called from server events
    cancelCall(72),
    deliveredCallRequest(73),
    callStarted(74),
    endCallRequest(75),
    endCall(76),
    getCalls(77),
    groupCallRequest(91),
    leaveCall(92),
    addCallParticipant(93),
    callParticipantJoined(94),
    removeCallParticipant(95),
    terminateCall(96), // never called from server events
    muteCallParticipant(97),
    unmuteCallParticipant(98),
    cancelGroupCall(99),
    activeCallParticipants(110),
    callSessionCreated(111),
    turnOnVideoCall(113),
    turnOffVideoCall(114),
    startRecording(121),
    stopRecording(122),
    getCallsToJoin(129),
    callClientErrors(153),
    callStickerSystemMessage(225),
    renewCallRequest(227),
    callInquiry(228),
    error(999);
    final int value;

    ChatMessageVOTypes(int value) {
        this.value = value;
    }
}
